export type ApplicationThemeColors = {
    background: string;
    backgroundLight: string;
    link: string;
    textMainBlack: string;
    textLowGray: string;
    textWhite: string;
    wclear: string;
    wclouds: string;
    wrain: string;
    wsnow: string;
    wthunderstorm: string;
    wdrizzle: string;
    wmist: string;
    searchBackground: string;
    climateBox: string;
    textToday: string;
    toggleHandle: string;
    toggleBackground: string;
    chartBorder: string;
};