import { ApplicationThemeColors } from "../protocols/Theme.types";

export const LightColors: ApplicationThemeColors = {
    background: '#EFEFEF',
    backgroundLight: '#FFFFFF',
    link: '#96A7F2',
    textMainBlack: '#222',
    textLowGray: '#C8C8C8',
    textWhite: '#FFFFFF',
    textToday: '#AFADAD',
    wclear: 'orange',
    wclouds: 'gray',
    wrain: 'blue',
    wsnow: 'lightgray',
    wthunderstorm: 'purple',
    wdrizzle: 'lightblue',
    wmist: 'lightgray',
    searchBackground: '#EDEDEF',
    climateBox: '#554c99',
    toggleHandle: '#FFF',
    toggleBackground: '#C8C8C8',
    chartBorder: '#D8D8D8',
}


export const DarkColors: ApplicationThemeColors = {
    background: '#212425',
    backgroundLight: '#181a1b',
    link: '#96A7F2',
    textMainBlack: '#FFF',
    textLowGray: '#C8C8C8',
    textWhite: '#FFFFFF',
    textToday: '#AFADAD',
    wclear: 'orange',
    wclouds: 'gray',
    wrain: 'blue',
    wsnow: 'lightgray',
    wthunderstorm: 'purple',
    wdrizzle: 'lightblue',
    wmist: 'lightgray',
    searchBackground: '#EDEDEF',
    climateBox: '#554c99',
    toggleHandle: '#181a1b',
    toggleBackground: '#373c3e',
    chartBorder: '#D8D8D8',
}